name = "Particle"
uuid = "76d689ba-cd5d-4c41-ab5a-af133e796eec"
authors = ["Kyungmin Lee <kyungmin.lee.42@gmail.com>"]
version = "0.1.0"

[deps]
ExactDiagonalization = "cf149b0a-e8f7-4f00-9ab4-03e4f5ec5cff"
LatticeTools = "8a267902-5e0e-44c3-8ef8-9b2b5c352816"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
